ERROR_STICKERS = (
    'CAACAgIAAxkBAANQZRr1S4gdMJs3iWV3psFhItAnm28AAkkCAAJWnb0KKpcMnQhTIQ4wBA',
    'CAACAgIAAxkBAANYZRr29Hx4en-dVgW5izSKXO_jJ60AAsURAAKwmrFIXVGdvpClV9owBA',
    'CAACAgIAAxkBAANZZRr3DzAfR-vrl-5Kw81cdOVCtcoAAgMAA_zS2A9ATlPUSf3ONjAE',
    'CAACAgEAAxkBAANaZRr3P_5Uqf4e9xktYFdnyrS0PFcAApEAAzgOghFl6ZFlwzLfbTAE',
    'CAACAgIAAxkBAANcZRr3bO22mRRibP0RkWrK69hEMZYAAscCAAJWnb0Kw8EO76xS0qgwBA',
    'CAACAgIAAxkBAANeZRr3p7Qbi4fsJBWXnNSemjyJUHYAAgIBAAJWnb0KTuJsgctA5P8wBA',

)

HELLO_STICKERS = (
    'CAACAgIAAxkBAAOSZRr9Z_sUIwSKJqkmLPXN2dav2UcAAgEBAAJWnb0KIr6fDrjC5jQwBA',
    'CAACAgIAAxkBAAOTZRr9tB2A9G3LDxV4Hwu-63VMh2EAAm8AA_cCyA_pM_2bB4KOMjAE',
    'CAACAgIAAxkBAAOUZRr90SecNno9JZedUKguZUuxiGYAArgAA_cCyA9GC5y04k4LODAE',
    'CAACAgIAAxkBAAOVZRr98gEU4OIPiuD3Qie5FsU2ZVYAAmkAA0QNzxdOntXIyIwiNTAE',
    'CAACAgIAAxkBAAOWZRr-G3yyBUKNacLJ8AsORFJJcskAAoIQAAKfcqBKNQ-sIScsd8QwBA',
    'CAACAgIAAxkBAAOXZRr-MUAIBNA2gq9FB2-m6hySDWIAApIBAAJWnb0Kn9AtCEIu1QUwBA'

)
